# Navigation Links
main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Resume
    url: uploads/resume.pdf
    weight: 20
#  - name: CV
#    url: uploads/cv.pdf
#    weight: 30
  - name: Publications
    url: '#featured'
    weight: 40
  - name: Projects
    url: '#projects'
    weight: 30
#  - name: Talks
#    url: '#talks'
#    weight: 40
  - name: Posts
    url: '#posts'
    weight: 180
  - name: Topics
    url: '#tags'
    weight: 190
  - name: Contact
    url: '#contact'
    weight: 200
