project:
  type: website
  output-dir: _site

website:
  title: "Glenn Matlin"
  page-footer:
    left: "&copy; 2025 Glenn Matlin. All rights reserved."
    right: "Published with [Quarto](https://quarto.org/)."

format:
  html:
    theme: cosmo
    css: styles.css