[project]
name = "glenn-academic-website"
version = "0.1.0"
description = "Academic website built with Quarto"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.0.0",
    "pyyaml>=6.0.0",
    "plotly>=5.0.0",
    "pandas>=2.0.0",
]
